"""
Knowledge Loader — generated by knowledge-hub v1.0.0
Generated at: 2026-04-30T05:56:49Z

Provides a clean API for loading, searching, and retrieving content from
installed knowledge bases found in the .knowledge directory.
"""

import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Optional dependencies for semantic search
# ---------------------------------------------------------------------------
_SEMANTIC_DEPS = True
try:
    import chromadb
    from chromadb.config import Settings as ChromaSettings
except ImportError:
    _SEMANTIC_DEPS = False

try:
    from sentence_transformers import SentenceTransformer
except ImportError:
    _SEMANTIC_DEPS = False


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class SearchResult:
    kb_name: str
    file_path: str
    title: str
    snippet: str
    score: float


@dataclass
class KBInfo:
    name: str
    description: str
    tags: list[str]
    version: str
    doc_count: int


# ---------------------------------------------------------------------------
# KnowledgeBase
# ---------------------------------------------------------------------------

class KnowledgeBase:
    def __init__(self, name: str, root_path: Path, metadata: dict):
        self.name = name
        self.description = metadata.get("description", "")
        self.tags = metadata.get("tags", [])
        self.version = metadata.get("version", "0.1.0")
        self.root_path = root_path
        self.documents: dict[str, str] = {}          # relative_path -> full text
        self._titles: dict[str, str] = {}            # relative_path -> extracted title
        self._token_index: dict[str, set[str]] = {}  # token -> set of paths

    # -- loading ----------------------------------------------------------

    def load(self) -> int:
        count = 0
        for root, _dirs, files in os.walk(self.root_path):
            for fname in files:
                if not fname.lower().endswith(".md"):
                    continue
                full_path = Path(root) / fname
                try:
                    text = full_path.read_text(encoding="utf-8")
                except (OSError, UnicodeDecodeError):
                    continue

                rel = str(full_path.relative_to(self.root_path)).replace("\\", "/")
                self.documents[rel] = text
                self._titles[rel] = self._extract_title(text)
                self._index_document(rel, text)
                count += 1
        return count

    def reload(self) -> int:
        self.documents.clear()
        self._titles.clear()
        self._token_index.clear()
        return self.load()

    # -- search -----------------------------------------------------------

    def search(self, query: str, top_k: int = 10) -> list[SearchResult]:
        query_tokens = self._tokenize(query)
        if not query_tokens:
            return []

        scored: list[tuple[float, str]] = []
        for path in self.documents:
            score = 0.0
            hit_tokens: set[str] = set()
            for qt in query_tokens:
                if qt in self._token_index and path in self._token_index[qt]:
                    score += 1.0
                    hit_tokens.add(qt)
            if score > 0:
                # boost exact phrase match
                if query.lower() in self.documents[path].lower():
                    score += 2.0
                # normalize by document length
                length = len(self.documents[path])
                if length > 0:
                    score = score * (min(len(query_tokens), len(hit_tokens)) / max(len(query_tokens), 1))
                scored.append((score, path))

        scored.sort(key=lambda x: x[0], reverse=True)
        results = []
        for score, path in scored[:top_k]:
            snippet = self._make_snippet(self.documents[path], query)
            results.append(SearchResult(
                kb_name=self.name,
                file_path=path,
                title=self._titles.get(path, path),
                snippet=snippet,
                score=round(score, 3),
            ))
        return results

    def list_documents(self) -> list[str]:
        return sorted(self.documents.keys())

    def get_document(self, path: str) -> str | None:
        return self.documents.get(path)

    # -- context window helper --------------------------------------------

    def get_context(self, query: str, max_chars: int = 4000, top_k: int = 5) -> str:
        results = self.search(query, top_k=top_k)
        if not results:
            return ""
        chunks = []
        total = 0
        for r in results:
            text = self.documents.get(r.file_path, "")
            if total + len(text) > max_chars:
                available = max_chars - total
                if available > 200:
                    text = text[:available] + "\n... (truncated)"
                else:
                    break
            chunks.append(f"## {r.title} ({self.name}/{r.file_path})\n\n{text}")
            total += len(text)
        return "\n\n---\n\n".join(chunks)

    # -- internals --------------------------------------------------------

    @staticmethod
    def _tokenize(text: str) -> list[str]:
        return re.findall(r"\w{2,}", text.lower())

    @staticmethod
    def _extract_title(text: str) -> str:
        m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
        return m.group(1).strip() if m else "Untitled"

    def _index_document(self, path: str, text: str) -> None:
        for token in set(self._tokenize(text)):
            self._token_index.setdefault(token, set()).add(path)

    @staticmethod
    def _make_snippet(text: str, query: str, window: int = 200) -> str:
        idx = text.lower().find(query.lower())
        if idx == -1:
            # try first query word
            first_word = query.split()[0].lower()
            idx = text.lower().find(first_word)
        if idx == -1:
            return text[:window] + ("..." if len(text) > window else "")
        start = max(0, idx - window // 2)
        end = min(len(text), idx + len(query) + window // 2)
        snippet = text[start:end]
        if start > 0:
            snippet = "..." + snippet
        if end < len(text):
            snippet = snippet + "..."
        return snippet


# ---------------------------------------------------------------------------
# KnowledgeLoader — top-level facade
# ---------------------------------------------------------------------------

class KnowledgeLoader:
    def __init__(self, knowledge_dir: str = ".knowledge"):
        self.knowledge_dir = Path(knowledge_dir).resolve()
        self.kbs: dict[str, KnowledgeBase] = {}
        self._semantic_index = None
        self._semantic_paths: list[tuple[str, str]] = []  # [(kb_name, rel_path), ...]
        self._embedding_model = None

    # -- loading ----------------------------------------------------------

    def load_all(self) -> list[str]:
        loaded = []
        state = self._read_state()
        entries = state.get("entries", {})

        for kb_name in sorted(entries.keys()):
            kb_path = self.knowledge_dir / kb_name
            if not kb_path.is_dir():
                continue
            meta = self._read_kb_metadata(kb_path)
            kb = KnowledgeBase(kb_name, kb_path, meta)
            count = kb.load()
            self.kbs[kb_name] = kb
            loaded.append(kb_name)

        return loaded

    def load(self, name: str) -> KnowledgeBase | None:
        kb_path = self.knowledge_dir / name
        if not kb_path.is_dir():
            return None
        meta = self._read_kb_metadata(kb_path)
        kb = KnowledgeBase(name, kb_path, meta)
        kb.load()
        self.kbs[name] = kb
        return kb

    def reload(self) -> list[str]:
        self.kbs.clear()
        self._semantic_index = None
        self._semantic_paths.clear()
        self._embedding_model = None
        return self.load_all()

    # -- keyword search ---------------------------------------------------

    def search(self, query: str, kb_name: Optional[str] = None,
               top_k: int = 10) -> list[SearchResult]:
        if kb_name:
            kb = self.kbs.get(kb_name) or self.load(kb_name)
            if kb is None:
                return []
            return kb.search(query, top_k=top_k)

        all_results: list[SearchResult] = []
        for kb in self.kbs.values():
            all_results.extend(kb.search(query, top_k=top_k))
        all_results.sort(key=lambda r: r.score, reverse=True)
        return all_results[:top_k]

    # -- semantic search --------------------------------------------------

    def semantic_search(self, query: str, top_k: int = 5) -> list[SearchResult]:
        if not _SEMANTIC_DEPS:
            print("[knowledge_loader] semantic_search requires: pip install chromadb sentence-transformers")
            print("[knowledge_loader] Falling back to keyword search.")
            return self.search(query, top_k=top_k)

        self._ensure_semantic_index()

        try:
            query_embedding = self._get_embedding_model().encode([query])[0]
        except Exception:
            return self.search(query, top_k=top_k)

        try:
            results = self._semantic_index.query(
                query_embeddings=[query_embedding.tolist()],
                n_results=min(top_k, len(self._semantic_paths)),
            )

            search_results = []
            distances = results.get("distances", [[]])[0]
            doc_ids = results.get("ids", [[]])[0]

            for dist, doc_id in zip(distances, doc_ids):
                if not doc_id:
                    continue
                kb_name, rel_path = self._doc_id_to_path(doc_id)
                text = self._get_document_text(kb_name, rel_path)
                snippet = KnowledgeBase._make_snippet(text, query)
                title = kb_rel_path = rel_path
                if kb_name in self.kbs:
                    title = self.kbs[kb_name]._titles.get(rel_path, rel_path)
                score = round(1.0 / (1.0 + dist), 4)
                search_results.append(SearchResult(
                    kb_name=kb_name,
                    file_path=rel_path,
                    title=title,
                    snippet=snippet,
                    score=score,
                ))

            return search_results
        except Exception:
            return self.search(query, top_k=top_k)

    # -- context helper ---------------------------------------------------

    def get_context(self, query: str, max_chars: int = 4000,
                    kb_name: Optional[str] = None, top_k: int = 5) -> str:
        if kb_name:
            kb = self.kbs.get(kb_name) or self.load(kb_name)
            if kb is None:
                return ""
            return kb.get_context(query, max_chars=max_chars, top_k=top_k)

        results = self.search(query, top_k=top_k)
        if not results:
            return ""

        chunks = []
        total = 0
        for r in results:
            text = self._get_document_text(r.kb_name, r.file_path)
            if total + len(text) > max_chars:
                available = max_chars - total
                if available > 200:
                    text = text[:available] + "\n... (truncated)"
                else:
                    break
            chunks.append(f"## {r.title} ({r.kb_name}/{r.file_path})\n\n{text}")
            total += len(text)

        return "\n\n---\n\n".join(chunks)

    # -- listing ----------------------------------------------------------

    def list_knowledge_bases(self) -> list[KBInfo]:
        infos = []
        for name, kb in self.kbs.items():
            infos.append(KBInfo(
                name=kb.name,
                description=kb.description,
                tags=kb.tags,
                version=kb.version,
                doc_count=len(kb.documents),
            ))
        return infos

    # -- internals --------------------------------------------------------

    def _read_state(self) -> dict:
        state_file = self.knowledge_dir / "install_state.json"
        if not state_file.exists():
            return {"entries": {}}
        try:
            return json.loads(state_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {"entries": {}}

    @staticmethod
    def _read_kb_metadata(kb_path: Path) -> dict:
        yaml_file = kb_path / "knowledge.yaml"
        if not yaml_file.exists():
            return {}
        try:
            import yaml
            data = yaml.safe_load(yaml_file.read_text(encoding="utf-8"))
            return data if isinstance(data, dict) else {}
        except Exception:
            return {}

    def _get_document_text(self, kb_name: str, rel_path: str) -> str:
        kb = self.kbs.get(kb_name)
        if kb:
            return kb.documents.get(rel_path, "")
        return ""

    def _ensure_semantic_index(self) -> None:
        if self._semantic_index is not None:
            return

        import chromadb
        self._semantic_index = chromadb.Client(
            ChromaSettings(anonymized_telemetry=False)
        )

        # try to reuse existing collection
        try:
            self._semantic_index.delete_collection("knowledge_hub")
        except Exception:
            pass

        collection = self._semantic_index.create_collection(
            name="knowledge_hub",
            metadata={"hnsw:space": "cosine"},
        )

        model = self._get_embedding_model()
        docs_to_index = []

        for kb_name, kb in self.kbs.items():
            for rel_path, text in kb.documents.items():
                doc_id = f"{kb_name}::{rel_path}"
                docs_to_index.append((doc_id, kb_name, rel_path, text))

        if not docs_to_index:
            return

        batch_size = 32
        for i in range(0, len(docs_to_index), batch_size):
            batch = docs_to_index[i:i + batch_size]
            texts = [b[3] for b in batch]
            # Truncate long texts for embedding
            truncated = [t[:8000] for t in texts]
            try:
                embeddings = model.encode(truncated)
            except Exception:
                return
            collection.add(
                ids=[b[0] for b in batch],
                embeddings=[e.tolist() for e in embeddings],
                documents=texts,
            )

        self._semantic_paths = [(b[1], b[2]) for b in docs_to_index]
        self._semantic_index = collection

    def _get_embedding_model(self):
        if self._embedding_model is None:
            from sentence_transformers import SentenceTransformer
            self._embedding_model = SentenceTransformer(
                "all-MiniLM-L6-v2"
            )
        return self._embedding_model

    @staticmethod
    def _doc_id_to_path(doc_id: str) -> tuple[str, str]:
        parts = doc_id.split("::", 1)
        if len(parts) == 2:
            return parts[0], parts[1]
        return "", doc_id
