import type { DashboardData } from "../api/client";

export function createMockDashboardData(
  overrides: Partial<DashboardData> = {},
): DashboardData {
  return {
    today_training: {
      is_training_day: true,
      completed: false,
      focus_area: "upper",
      recommendation: "Apply progressive overload.",
    },
    recovery: {
      sleep_hours: 7.5,
      fatigue_score: 3,
      pain_score: 1,
      stress_score: 2,
      log_date: "2026-05-04",
    },
    nutrition: {
      calories_kcal: 2200,
      protein_g: 150,
      carbs_g: 250,
      fat_g: 70,
      water_liters: 2.5,
      body_weight_kg: 73,
      log_date: "2026-05-04",
    },
    goal_progress: {
      goal_type: "muscle_gain",
      current_weight_kg: 73,
      target_weight_kg: 85,
      weight_gap_kg: 12,
      days_remaining: 90,
      progress_label: "正常",
      summary: "当前体重 73kg，目标 85kg，还差 12kg",
      actual_weekly_weight_change_kg: 0.3,
      required_weekly_weight_change_kg: 0.5,
      current_muscle_kg: 32,
      target_muscle_kg: 35,
      muscle_gap_kg: 3,
    },
    weight_trend: [
      { log_date: "2026-05-01", body_weight_kg: 72.5 },
      { log_date: "2026-05-02", body_weight_kg: 72.8 },
      { log_date: "2026-05-03", body_weight_kg: 73.0 },
      { log_date: "2026-05-04", body_weight_kg: 73.1 },
    ],
    body_metrics: {
      body_weight_kg: 73,
      body_fat_rate_pct: 15,
      body_fat_kg: 10.95,
      muscle_weight_kg: 32,
      skeletal_muscle_kg: 34,
      body_water_kg: 45,
      protein_kg: 12,
      minerals_kg: 4,
      left_upper_muscle_kg: 3.0,
      right_upper_muscle_kg: 3.1,
      left_lower_muscle_kg: 6.0,
      right_lower_muscle_kg: 6.1,
      trunk_muscle_kg: 15.8,
      left_upper_fat_kg: 0.7,
      right_upper_fat_kg: 0.7,
      left_lower_fat_kg: 1.6,
      right_lower_fat_kg: 1.7,
      trunk_fat_kg: 5.4,
      waist_cm: 75,
      hip_cm: 93,
      inbody_score: 80,
      bmr_kcal: 1750,
      bmi: 21.8,
      smi: 10.2,
      whr: 0.81,
      body_assessment: "力量之星",
      height_cm: 183,
    },
    cost_status: {
      monthly_budget_rmb: 30,
      spent_rmb: 0.5,
      remaining_rmb: 29.5,
    },
    ...overrides,
  };
}
